name: Database Daily Cleanup

on:
  schedule:
    - cron: '0 3 * * *' 
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Debug URL
        run: echo "The URL is ${{ secrets.API_URL }}"

      - name: Trigger DB Cleanup
        run: |
          curl -i -X POST "${{ secrets.API_URL }}/api/cleanup" \
          -H "x-token: ${{ secrets.CLEANUP_TOKEN }}"
